export const FETCH_ACTIVITIES = "FETCH_ACTIVITIES";
export const EDIT_ACTIVITY = "EDIT_ACTIVITY";
export const DELETE_ACTIVITY = "DELETE_ACTIVITY";
export const ASCENDING_ACTIVITIES = "ASCENDING_ACTIVITIES";
export const DESCENDING_ACTIVITIES = "DESCENDING_ACTIVITIES";
